version: 1.0.{build}.0

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '1.0.0-beta'

configuration: Release

platform: Any CPU

before_build:
- nuget restore

build:
  project: Phamhilator.sln
  parallel: true
  verbosity: minimal
