version: 2.0.{build}.0

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '2.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.0.0-beta'

configuration: Release

platform: Any CPU

before_build:
- nuget restore
  
artifacts:
- path: Yam.Core\bin\Release\ChectExchange.Net.dll
  name: ChatExchange.Net.Net.dll
- path: Yam.Core\bin\Release\CsQuery.dll
  name: CsQuery.dll
- path: Yam.Core\bin\Release\ServiceStack.Text.Dll
  name: ServiceStack.Text.dll
- path: Yam.Core\bin\Release\websocket-sharp.dll
  name: websocket-sharp.dll
- path: Yam.Core\bin\Release\Yam.Core.dll
  name: Yam.Core.dll
  
- path: Pham\bin\Release\Pham.exe
  name: Pham.exe
  
- path: NLP\bin\Release\NLP.dll
  name: NLP.dll

build:
  project: Phamhilator.sln
  parallel: true
  verbosity: minimal
