//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phamhilator.Pham.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phamhilator.Pham.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///to
        ///you
        ///is
        ///and
        ///it
        ///in
        ///of
        ///that
        ///this
        ///have
        ///for
        ///not
        ///am
        ///your
        ///my
        ///on
        ///can
        ///with
        ///are
        ///file
        ///as
        ///if
        ///do
        ///be
        ///code
        ///an
        ///data
        ///use
        ///will
        ///we
        ///would
        ///class
        ///page
        ///using
        ///table
        ///image
        ///app
        ///user
        ///server
        ///but
        ///from
        ///function
        ///view
        ///was
        ///or
        ///java
        ///like
        ///application
        ///array
        ///php
        ///error
        ///project
        ///form
        ///list
        ///there
        ///want
        ///when
        ///one
        ///string
        ///object
        ///at
        ///value
        ///method
        ///text
        ///how
        ///id
        ///what
        ///get
        ///nbsp
        ///files
        ///xml
        ///so
        ///database
        ///which
        ///time
        ///thread
        ///button
        ///service
        ///need
        ///web
        ///all
        ///query
        ///should
        ///some
        ///by
        ///test        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOStopwordCorpus {
            get {
                return ResourceManager.GetString("SOStopwordCorpus", resourceCulture);
            }
        }
    }
}
